# Dataset parameters
context_length: 16 # Due because the program run on a CPU
max_snippets: 1000

# Model parameters
embed_dimension: 128
hidden_dimension: 128
num_layers: 2
dropout: 0.1

# Training parameters
batch_size: 32 
epochs: 10
lr: 0.00005 
