# Dataset parameters
context_length: 32
max_snippets: 10000

# Model parameters
embed_dimension: 256
hidden_dimension: 256
num_layers: 3
dropout: 0.2

# Training parameters
batch_size: 32 
epochs: 10
lr: 0.0001
